sudo: false
language: node_js
node_js: stable
branches:
  only:
    - master
before_install:
  - npm install -g hexo-cli
install:
  - npm install
before_script:
  - sed -i "s~git@github.com:~https://${GH_TOKEN}@github.com/~" _config.yml || exit 1
script:
  - hexo clean
  - hexo generate
  - hexo deploy